# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cfeaab14e6d65938072f52114b773f00fcbca812baea8fd2bc67f9c8abd67063359b9647009d23c1b1ca441bd276cdaf55aaaa066dd32d21f39a261a6c40edc3

test:
  secret_key_base: 9590255fa34992e4ddcb5f679bfa18e258d5964d81f92ab473e747d549f6e510fa0a5edaa62e031aa74ac66a6ba5d12fadd415e4c4dfab5b090266d5013ad994

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
